version: '3'

services:

  # self hosted registry or build from current directory
  my_container:
    # or build: ./
    image: registry_ip:port/project/image_name:image_version
    container_name: my_container_name
    # define user and group to run the image
    user: "${UID}:${GID}"

    # map port host:container
    ports:
      - "8000:8000"
    restart: always

    # define environment variables, these are defined in .env file
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - DEBUG=${DEBUG}
    depends_on:
      - mysql
      - redis
    networks:
      - db_net
      - redis_net

  # use image from docker hub
  mysql:
    image: mysql:5.7
    container_name: my_container_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOTPWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - db_net

  redis:
    image: redis:2.8
    container_name: my_container_redis
    restart: always
    networks:
      - redis_net

networks:
  db_net:
  redis_net:
